-- ─────────────────────────────────────────────────────────────────────────
-- Pipeline schema migration 0004 — add 'slab_rejected' tight_crop_method
-- ─────────────────────────────────────────────────────────────────────────
-- TightCrop.swift now runs OCR on the top 25% of each rectified crop and
-- looks for grading-label keywords (PSA, BGS, SGC, GEM MT, MINT, etc.).
-- When detected, the candidate's tight_crop_method is set to
-- 'slab_rejected' — the rectified image is still written for audit
-- purposes, but the AUTO gate excludes it because crop_method !=
-- 'vision_rect'.
--
-- Aspect alone can't distinguish slabs from cards (both ~0.71 portrait);
-- OCR-based detection of the grading label is the discriminating signal.
-- ─────────────────────────────────────────────────────────────────────────

alter table public.pipeline_image_candidates
    drop constraint if exists pipeline_image_candidates_tight_crop_method_check;

alter table public.pipeline_image_candidates
    drop constraint if exists pipeline_image_candidates_tight_crop_method_check1;

-- The original constraint name is auto-generated by Postgres. Drop any
-- variant of the check constraint on tight_crop_method by re-asserting:
do $$
declare
    cn text;
begin
    for cn in
        select conname
        from pg_constraint
        where conrelid = 'public.pipeline_image_candidates'::regclass
          and pg_get_constraintdef(oid) ilike '%tight_crop_method%'
    loop
        execute format('alter table public.pipeline_image_candidates drop constraint %I', cn);
    end loop;
end $$;

alter table public.pipeline_image_candidates
    add constraint pipeline_image_candidates_tight_crop_method_check
    check (tight_crop_method is null
           or tight_crop_method in ('vision_rect', 'center_57', 'uncropped', 'slab_rejected'));
