#!/usr/bin/env python3
"""
migrate_bobaid_to_v3.py — one-shot migration to extend bobaId with
the WEAPON field (catalog name: `element`, BoBA-canonical: Weapon).

CONTEXT
-------
The 4-field formula `cardNumber-hero-treatment-variation` collided on
FIRE-weapon vs GLOW-weapon variant siblings that share otherwise-
identical (cardNumber, hero, treatment, variation). The catalog
worked around this by assigning distinct cardNumbers to the weapon
variants (GLBF-43 = GLOW, GLBF-85 = FIRE for the same physical card
structure). Adding weapon to the formula removes that workaround.

WHAT THIS DOES
--------------
1. Walks assets/data/cards.json, computes both the OLD 4-field bobaId
   and the NEW 5-field bobaId for every card.
2. Writes the new bobaId field in cards.json.
3. Emits a mapping JSON {old_bobaId: new_bobaId} so the Supabase
   migration can UPDATE all user_cards / deck_cards / show_cards /
   card_corrections / card_image_overrides rows.
4. Emits Supabase migration SQL ready to apply via the Supabase MCP.

The script is IDEMPOTENT — re-running on a catalog that already has
the new bobaId values is a no-op. Run via:

    python3 pipeline/scripts/migrate_bobaid_to_v3.py \\
        --catalog assets/data/cards.json \\
        --mapping-out /tmp/bobaid-v2-to-v3.json \\
        --sql-out    /tmp/bobaid-v3-migration.sql

OUTPUT
------
- /tmp/bobaid-v2-to-v3.json — every {old_bobaId: new_bobaId} for rows
  that actually changed (i.e. cards with non-empty element).
- /tmp/bobaid-v3-migration.sql — paste into the Supabase SQL editor
  or apply via mcp__claude_ai_Supabase__execute_sql.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Mirror the OLD formula so we can compute it for old-bobaId mapping.
def boba_id_v2(card: dict) -> str:
    cn    = str(card.get("cardNumber") or "").strip()
    hero  = str(card.get("hero") or card.get("name") or "").strip()
    treat = str(card.get("treatment") or "").strip()
    var   = str(card.get("variation") or "").strip()
    return f"{cn}-{hero}-{treat}-{var}"

# Import the new formula from the canonical source so we never drift.
def boba_id_v3(card: dict) -> str:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "scripts"))
    from boba_id import boba_id  # noqa: WPS433
    return boba_id(card)


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--catalog", required=True)
    p.add_argument("--mapping-out", required=True,
                   help="Where to write the {old_bobaId: new_bobaId} map")
    p.add_argument("--sql-out", required=True,
                   help="Where to write the Supabase migration SQL")
    return p.parse_args()


SUPABASE_TABLES = [
    # (table_name, column_name) — every Supabase table that stores a
    # bobaId. From supabase_schema.sql + pipeline/migrations/.
    ("user_cards",                 "boba_id"),
    ("card_corrections",           "boba_id"),
    ("card_image_overrides",       "boba_id"),
    ("show_cards",                 "boba_id"),
    ("deck_cards",                 "boba_id"),
    ("pipeline_image_candidates",  "target_boba_id"),
    ("pipeline_image_candidates",  "recognized_boba_id"),
    ("pipeline_image_candidates",  "collision_with_boba_id"),
    ("pipeline_card_images",       "boba_id"),
]


def build_sql(mapping: dict[str, str]) -> str:
    """Generate UPDATE statements. Uses a temporary table to do the
    join efficiently (vs N tiny UPDATEs). One transaction per table
    so a failure on one doesn't half-migrate another."""
    lines = []
    lines.append("-- bobaId v2 → v3 migration (adds weapon as 5th field)")
    lines.append("-- Generated by pipeline/scripts/migrate_bobaid_to_v3.py")
    lines.append("-- DECISIONS.md #057 documents the rationale.")
    lines.append("")
    lines.append("BEGIN;")
    lines.append("")
    lines.append("-- Temp mapping table.")
    lines.append("CREATE TEMP TABLE bobaid_v2_to_v3 (")
    lines.append("  old_bobaid TEXT PRIMARY KEY,")
    lines.append("  new_bobaid TEXT NOT NULL")
    lines.append(");")
    lines.append("")
    lines.append("INSERT INTO bobaid_v2_to_v3 (old_bobaid, new_bobaid) VALUES")
    rows = []
    for old, new in sorted(mapping.items()):
        old_esc = old.replace("'", "''")
        new_esc = new.replace("'", "''")
        rows.append(f"  ('{old_esc}', '{new_esc}')")
    lines.append(",\n".join(rows) + ";")
    lines.append("")
    for table, col in SUPABASE_TABLES:
        lines.append(f"-- Update {table}.{col}")
        lines.append(f"UPDATE {table} SET {col} = m.new_bobaid")
        lines.append(f"FROM bobaid_v2_to_v3 m")
        lines.append(f"WHERE {table}.{col} = m.old_bobaid;")
        lines.append("")
    lines.append("COMMIT;")
    lines.append("")
    lines.append("-- Verification queries (run AFTER commit to sanity-check):")
    for table, col in SUPABASE_TABLES:
        lines.append(f"-- SELECT count(*) FROM {table} WHERE {col} LIKE '%-%-%-%' AND {col} NOT LIKE '%-%-%-%-%';")
    return "\n".join(lines) + "\n"


def main():
    args = parse_args()
    catalog_path = Path(args.catalog)
    with open(catalog_path) as f:
        cards = json.load(f)
    print(f"[migrate] catalog: {len(cards)} cards", flush=True)

    mapping: dict[str, str] = {}    # old_bobaId → new_bobaId
    catalog_writes = 0              # how many cards' stored bobaId field changed
    weapon_distribution = {}        # counts by element value
    no_change = 0                   # cards where new == old
    collisions: list[tuple[str, str, str]] = []  # bobaId collisions in NEW formula

    seen_new_bid: dict[str, str] = {}
    for c in cards:
        old_bid = boba_id_v2(c)
        new_bid = boba_id_v3(c)
        if old_bid == new_bid:
            no_change += 1
        elif old_bid != new_bid:
            mapping[old_bid] = new_bid
        # Detect collisions in the NEW formula.
        if new_bid in seen_new_bid:
            collisions.append((new_bid, seen_new_bid[new_bid], c.get("bobaId") or old_bid))
        else:
            seen_new_bid[new_bid] = c.get("bobaId") or old_bid
        # Update stored bobaId field.
        if c.get("bobaId") != new_bid:
            c["bobaId"] = new_bid
            catalog_writes += 1
        # Count weapon distribution.
        e = (c.get("element") or "").upper() or "<empty>"
        weapon_distribution[e] = weapon_distribution.get(e, 0) + 1

    # Report.
    print(f"[migrate] cards with bobaId field updated: {catalog_writes}")
    print(f"[migrate] old==new (unchanged): {no_change}")
    print(f"[migrate] mapping entries (old→new): {len(mapping)}")
    print(f"[migrate] new-formula collisions: {len(collisions)}")
    if collisions:
        print("\n[migrate] COLLISIONS — these new bobaIds clash. Catalog may have")
        print("                       remaining duplicate cards that the new formula")
        print("                       can't distinguish even with weapon included:")
        for new, first, second in collisions[:20]:
            print(f"  new={new!r}")
            print(f"    first occurrence:  {first!r}")
            print(f"    second occurrence: {second!r}")
        if len(collisions) > 20:
            print(f"  … and {len(collisions) - 20} more")

    print(f"\n[migrate] weapon distribution:")
    for w, n in sorted(weapon_distribution.items(), key=lambda x: -x[1]):
        print(f"  {w:<10} {n}")

    # Write catalog back.
    if catalog_writes:
        catalog_path.write_text(json.dumps(cards, indent=2) + "\n")
        print(f"\n[migrate] wrote updated catalog: {catalog_path}")

    # Write mapping.
    mapping_path = Path(args.mapping_out)
    mapping_path.write_text(json.dumps(mapping, indent=2, sort_keys=True))
    print(f"[migrate] wrote mapping: {mapping_path} ({len(mapping)} entries)")

    # Write SQL.
    sql_path = Path(args.sql_out)
    sql_path.write_text(build_sql(mapping))
    print(f"[migrate] wrote SQL: {sql_path}")

    return 1 if collisions else 0


if __name__ == "__main__":
    sys.exit(main())
