#!/usr/bin/env python3
"""
build_blog_digest.py — rewrite docs/blog-digest.md from docs/blog-feed.json.

A short markdown file the autonomous /loop reads at tick start.
One line per post (date · title · link) + an optional excerpt
sentence. Keeps the loop's source-of-work mining cheap — no JSON
parsing required from the loop side.

Run:
  python3 scripts/build_blog_digest.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

FEED   = Path("docs/blog-feed.json")
DIGEST = Path("docs/blog-digest.md")


def shorten(text: str, limit: int = 200) -> str:
    if not text:
        return ""
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"


def main() -> int:
    if not FEED.exists():
        print(f"ERROR: {FEED} missing — run scripts/refresh_blog.py first.",
              file=sys.stderr)
        return 1
    bundle = json.loads(FEED.read_text())
    posts  = bundle.get("posts") or []
    src    = bundle.get("source") or "https://bobattlearena.com/blog"
    last   = bundle.get("lastUpdated") or ""

    lines: list[str] = []
    lines.append("# BoBA Blog Digest")
    lines.append("")
    lines.append(
        f"> Auto-generated by `scripts/build_blog_digest.py` from "
        f"`docs/blog-feed.json`. Last refreshed **{last}**. Source: {src}."
    )
    lines.append("")
    lines.append(
        "Use this file at the top of any autonomous /loop tick to "
        "scan what the BoBA team has been publishing. Posts with "
        "release dates, tournament announcements, or rules updates "
        "are the most useful mining targets — convert them into "
        "concrete app work (catalog data, events.json curated rows, "
        "Learn-tab article tweaks, etc.)."
    )
    lines.append("")
    lines.append(f"**{len(posts)} posts.**")
    lines.append("")

    for post in posts:
        date    = post.get("date") or "—"
        title   = post.get("title") or "(untitled)"
        url     = post.get("url") or ""
        excerpt = shorten(post.get("excerpt") or "", 220)
        lines.append(f"### {date} — [{title}]({url})")
        if excerpt:
            lines.append("")
            lines.append(f"> {excerpt}")
        lines.append("")

    DIGEST.parent.mkdir(parents=True, exist_ok=True)
    DIGEST.write_text("\n".join(lines).rstrip() + "\n")
    print(f"Wrote {DIGEST} — {len(posts)} posts.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
