#!/usr/bin/env python3
"""
Build the banned-words list used to gate username creation.

Two outputs from one source list:

  - BOBAPlaybook/banned-words.json — bundled into the iOS app for the
    instant client-side red pill on the username TextField.
  - SQL INSERT statements written to stdout — apply via Supabase MCP
    (or psql) to populate the `banned_words` table (the authoritative
    server-side gate; the bundled JSON is for UX only).

Source: LDNOOBW EN list (Shutterstock, Apache 2.0). Filtered to ≥4
characters to reduce Scunthorpe-style false positives ("ass" inside
"class", "tit" inside "title", etc.). For a username (which is a
substring search), shorter terms create more collateral damage than
they prevent. We bias toward catching the real slurs and leave the
mild-profanity-as-substring edge cases.

Custom additions live in scripts/custom_banned.txt — one word per
line, comments allowed with #. Use this for project-specific terms
the LDNOOBW list misses.

Usage:
  python3 scripts/build_banned_words.py            # writes JSON only
  python3 scripts/build_banned_words.py --emit-sql # also writes SQL to stdout
"""

import argparse
import json
import sys
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
JSON_OUT = REPO_ROOT / "BOBAPlaybook" / "banned-words.json"
CUSTOM_TXT = REPO_ROOT / "scripts" / "custom_banned.txt"

LDNOOBW_URL = (
    "https://raw.githubusercontent.com/LDNOOBW/"
    "List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master/en"
)

MIN_LEN = 4  # shorter terms cause more false positives than they catch


def fetch_ldnoobw() -> list[str]:
    print(f"Fetching {LDNOOBW_URL} …", file=sys.stderr)
    req = urllib.request.Request(LDNOOBW_URL, headers={"User-Agent": "boba-playbook-build"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        body = resp.read().decode("utf-8")
    words = [w.strip().lower() for w in body.splitlines() if w.strip()]
    print(f"  {len(words)} raw words from LDNOOBW", file=sys.stderr)
    return words


def load_custom() -> list[str]:
    if not CUSTOM_TXT.exists():
        return []
    out = []
    for line in CUSTOM_TXT.read_text().splitlines():
        line = line.split("#", 1)[0].strip().lower()
        if line:
            out.append(line)
    print(f"  {len(out)} words from {CUSTOM_TXT.name}", file=sys.stderr)
    return out


def normalize(words: list[str]) -> list[str]:
    """Drop short / non-ascii / multi-word entries. Username regex is
    [a-z0-9_-]+, so any candidate with chars outside that set can never
    be a username substring anyway — no point storing them."""
    seen = set()
    out = []
    for w in words:
        if len(w) < MIN_LEN:
            continue
        if not all(c.isascii() and (c.isalnum() or c in "_-") for c in w):
            continue
        if w in seen:
            continue
        seen.add(w)
        out.append(w)
    return sorted(out)


def write_json(words: list[str]) -> None:
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(json.dumps(words, separators=(",", ":")))
    print(f"Wrote {len(words)} words → {JSON_OUT.relative_to(REPO_ROOT)}", file=sys.stderr)


def emit_sql(words: list[str]) -> None:
    """Generate idempotent INSERT statements. Source defaults to
    'ldnoobw' for fetched words; custom-list words are tagged 'custom'
    so admins can distinguish them in the table."""
    print("-- Generated by scripts/build_banned_words.py")
    print("-- Apply via Supabase MCP execute_sql or psql.")
    print("BEGIN;")
    # Wipe + repopulate so the table mirrors the source list exactly.
    print("TRUNCATE TABLE banned_words;")
    custom = set(load_custom_only_normalized())
    rows = []
    for w in words:
        source = "custom" if w in custom else "ldnoobw"
        # Escape single quotes by doubling.
        safe = w.replace("'", "''")
        rows.append(f"  ('{safe}', '{source}')")
    # Chunk into INSERTs of 500 rows to keep each statement reasonable.
    chunk = 500
    for i in range(0, len(rows), chunk):
        print("INSERT INTO banned_words (word, source) VALUES")
        print(",\n".join(rows[i:i + chunk]) + ";")
    print("COMMIT;")


def load_custom_only_normalized() -> list[str]:
    return normalize(load_custom())


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--emit-sql", action="store_true",
                        help="Print SQL INSERT statements to stdout")
    args = parser.parse_args()

    raw = fetch_ldnoobw() + load_custom()
    words = normalize(raw)
    print(f"  {len(words)} after normalize (≥{MIN_LEN} chars, ascii, alnum/_/-)",
          file=sys.stderr)
    write_json(words)
    if args.emit_sql:
        emit_sql(words)


if __name__ == "__main__":
    main()
